// This file was auto-generated by CMake
#pragma once

// The absolute path to the root of the repository.
#ifndef MX_REPO_ROOT_PATH
#define MX_REPO_ROOT_PATH "/home/flaskposto/Documents/Projects/mfpr/mxml_test/libs/mx"
#endif
