name: CMake on multiple platforms

on:
  push:
    branches: [ "feature-9-cicdwindows-setup" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, cl]
        mx_rebuild: [true, false]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            mx_rebuild: true
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            mx_rebuild: false
        exclude:
          - os: windows-latest
            c_compiler: gcc
            mx_rebuild: false
          - os: ubuntu-latest
            c_compiler: cl
            mx_rebuild: true

    steps:
    - uses: actions/checkout@v3

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
  
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DREBUILD_MX=${{ matrix.mx_rebuild }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}
