name: Deploy-Master

on: 
  workflow-call:
    # push:
    #tags:
    #  - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write 
  discussions: write

jobs:
  get-version:
    outputs:
      v-major: ${{ steps.major.outputs.major }}
      v-minor: ${{ steps.major.outputs.major }}
      patch: ${{ steps.major.outputs.major }}
    steps:
      - uses: little-core-labs/get-git-tag@v3.0.2
        id: major
        with:
          tagRegex: "v(?<major>*).(?<minor>*).(?<patch>*)*" 

  ubuntu-build-test:
    needs: get-version
    uses: ./.github/workflows/wf-main.yml
    with: 
      os: ubuntu-latest
      c-compiler: gcc
      cxx-compiler: g++
      mx-rebuild: false
      build-tests: true
      build-type: Release
      upload-artifact: true
      v-major: jobs.
  
  windows-build-test:
    needs: get-version
    uses: ./.github/workflows/wf-main.yml
    with: 
      os: windows-latest
      c-compiler: cl
      cxx-compiler: cl
      mx-rebuild: false
      build-tests: true
      build-type: Release
      upload-artifact: true

  deploy-ubuntu:
    environment:
      name: production
    needs: ubuntu-build-test
    runs-on: ubuntu-latest
    steps:
      - name: Get Gui
        uses: actions/download-artifact@v4
        with:
          name: mfpg_gui_artifact_ubuntu
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
         files: | 
           mfpg_gui_linux
           mfpg_cli_linux
      
  deploy-windows:
    environment:
      name: production
    needs: windows-build-test
    runs-on: windows-latest
    steps:
      - name: Get Gui
        uses: actions/download-artifact@v4
        with:
          name: mfpg_gui_artifact_windows
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
         files: | 
           mfpg_gui_x86.exe
           mfpg_cli_x86.exe
