name: Deploy-Master

on: 
  push:
  workflow_dispatch:

jobs:
  ubuntu-build-test:
    runs-on: ubuntu-latest
    environment:
      name: production
    uses: ./.github/workflows/wf-main.yml
    with: 
      os: ubuntu-latest
      c-compiler: gcc
      cxx-compiler: g++
      mx-rebuild: false
      build-tests: true
      build-type: Release
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
         files: mfpg/mfpg_build/mfpg_gui
      
    
