name: Deploy-Master

on: 
  push:
  workflow_dispatch:

jobs:
  ubuntu-build-test:
    uses: ./.github/workflows/wf-main.yml
    with: 
      os: ubuntu-latest
      c-compiler: gcc
      cxx-compiler: g++
      mx-rebuild: false
      build-tests: true
      build-type: Release
      upload-artifact: true

  deploy-ubuntu:
    environment:
      name: production
    needs: ubuntu-build-test
    runs-on: ubuntu-latest
    steps:
      - name: Get Gui
        uses: actions/download-artifact@v4
        with:
          name: mfpg_gui_artifact
          path: mfpg_artifacts
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
         files: mfpg_artifacts/mfpg_gui_artifact
      
    
