name: Merge to Master

on:
  pull_request: 
    branches: [ "master" ]

jobs:
  ubuntu-build-test:
    uses: ./.github/workflows/ubuntu.yml
    with: 
      mx-rebuild: false
      build-tests: true
      build-type: Release
  
  windows-build-test:
    uses: ./.github/workflows/windows.yml
    with: 
      mx-rebuild: false
      build-tests: true
      build-type: Release
