name: CMake on multiple platforms

on:
  push:
    branches: [ "feature-9-cicdwindows-setup" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu-build:
    uses: ./.github/workflows/wf-main.yml
    with: 
      os: ubuntu-latest
      c-compiler: gcc
      cxx-compiler: g++
      mx-rebuild: false
      build-type: Release