name: CMake on multiple platforms

on:
  push:
    branches: [ "feature-9-cicdwindows-setup" ]
  pull_request:
    branches: [ "master" ]

jobs:
  windows-build:
    uses: ./.github/workflows/wf-main.yml
    with: 
      os: ubuntu-latest
      c-compiler: cl
      cxx-compiler: cl
      mx-rebuild: false
      build-type: Release