name: ver 

on: 
  push:

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      v-major: ${{ steps.tag.outputs.major }}
      v-minor: ${{ steps.tag.outputs.minor }}
      patch: ${{ steps.tag.outputs.patch }}
    steps:
      - uses: little-core-labs/get-git-tag@v3.0.2
        id: tag
        with:
          tagRegex: "v(?<major>).(?<minor>).(?<patch>)*" 

  output-ver:
    runs-on: ubuntu-latest
    needs: get-version
    steps:
        - name: output ver
          run: echo ${{ needs.get-version.outputs.major }}


