on:
    workflow_call:
        inputs:
            os:
                required: true
                type: string
            c-compiler:
                required: true
                type: string
            cxx-compiler:
                required: true
                type: string
            mx-rebuild:
                required: false
                type: boolean
                default: false
            build-tests:
                required: false
                type: boolean
                default: true
            build-type:
                required: false
                type: string
                default: Release

jobs:
    build:
        runs-on: ${{ inputs.os }}
        steps:

            #Building WX on windows takes some time, cache when possible
            - name: Cache WX x86 Windows
              if: inputs.os == 'windows-latest'
              id: cache-wx-x86
              uses: actions/cache@v3
              with:
                path: C:/Program Files (x86)/wxWidgets
                key: wx-build-3.2.4-windows-x86
                restore-keys: |
                  wx-build-3.2.4-windows-x86

            - name: Checkout WX Windows
              if: inputs.os == 'windows-latest' && steps.cache-wx-x86.outputs.cacher-hit != 'true'
              uses: actions/checkout@v3
              with:
                repository: WxWidgets/WxWidgets
                ref: v3.2.4
                path: ${{ github.workspace }}/wxWidgets
                submodules: 'true'

            - name: Configure WX x86 Windows
              if: inputs.os == 'windows-latest' && steps.cache-wx-x86.outputs.cacher-hit != 'true'
              run: >
                cmake ${{ github.workspace  }}/WxWidgets
                -DwxBUILD_SHARED=OFF
                -B ${{ github.workspace }}/wx-build-windows-x86

            - name: Build WX x86 Windows
              if: inputs.os == 'windows-latest' && steps.cache-wx-x86.outputs.cacher-hit != 'true'
              run: > 
                cmake --build ${{ github.workspace }}/wx-build-windows-x86 
                --target install --config Release 

            #On ubuntu we get the packages through apt.
            - name: Get GTK Ubuntu
              if: inputs.os == 'ubuntu-latest'
              run: |
                sudo apt-get install libgtk-3-dev
                sudo apt-get install libwxgtk3.0-gtk3-0v5
                sudo apt-get install libwxgtk3.0-gtk3-dev
            
            - uses: actions/checkout@v3
              with:
                path: ${{ github.workspace }}/mfpg
                submodules: 'true'

            - name: Configure MFPG
              run: >
                cmake ${{ github.workspace }}/mfpg
                -B ${{ github.workspace }}/mfpg_build
                -DCMAKE_CXX_COMPILER=${{ inputs.cxx-compiler }}
                -DCMAKE_C_COMPILER=${{ inputs.c-compiler }}
                -DCMAKE_BUILD_TYPE=${{ inputs.build-type }}
                -DREBUILD_MX=${{ inputs.mx-rebuild }}
                -DBUILD_TESTS=${{ inputs.build-tests }}
                -A x64
                -DWXW_ROOT_DIR="C:/Program Files (x86)/wxWidgets"
                -DWXW_LIB_DIR="C:/Program Files (x86)/wxWidgets/lib/vc_x64_lib"
                -DWXW_INC_DIR="C:/Program Files (x86)/wxWidgets/include"
                
            - name: Build MFPG
              run: > 
                cmake 
                --build ${{ github.workspace }}/mfpg_build 
                --config ${{ inputs.build-type }}

            - name: Test MFPG
              working-directory: ${{ github.workspace }}/mfpg_build
              run: >
                ctest 
                --output-on-failure
                --build-config ${{ inputs.build-type }}
