on:
    workflow_call:
        inputs:
            os:
                required: true
                type: string
            c-compiler:
                required: true
                type: string
            cxx-compiler:
                required: true
                type: string
            mx-rebuild:
                required: false
                type: boolean
                default: false
            build-tests:
                required: false
                type: boolean
                default: true
            build-type:
                required: false
                type: string
                default: Release
            upload-artifact:
                required: false
                type: boolean
                default: false
            version:
                required: false
                type: string
                default: "0.0.0"

jobs:
    build:
        runs-on: ${{ inputs.os }}
        steps:
          #Different behaviour for windows and ubuntu when installing wxWidgets.
            - name: Cache WX x86 Windows
              if: inputs.os == 'windows-latest'
              id: cache-wx-x86
              uses: actions/cache@v3
              with:
                path: C:/Program Files (x86)/wxWidgets
                key: wx-build-3.2.4-windows-x86
                restore-keys: |
                  wx-build-3.2.4-windows-x86

            - name: Checkout WX x86 Windows
              if: inputs.os == 'windows-latest' && steps.cache-wx-x86.outputs.cache-hit != 'true'
              uses: actions/checkout@v3
              with:
                repository: WxWidgets/WxWidgets
                ref: v3.2.4
                path: ${{ github.workspace }}/wxWidgets
                submodules: 'true'

            - name: Configure WX x86 Windows
              if: inputs.os == 'windows-latest' && steps.cache-wx-x86.outputs.cache-hit != 'true'
              run: >
                cmake ${{ github.workspace  }}/WxWidgets
                -DwxBUILD_SHARED=OFF
                -B ${{ github.workspace }}/wx-build-windows-x86

            - name: Build WX x86 Windows
              if: inputs.os == 'windows-latest' && steps.cache-wx-x86.outputs.cache-hit != 'true'
              run: > 
                cmake --build ${{ github.workspace }}/wx-build-windows-x86 
                --target install --config Release 

            - name: Get GTK Ubuntu
              if: inputs.os == 'ubuntu-latest'
              run: |
                sudo apt-get update
                sudo apt-get install libgtk-3-dev
            
            - name: tar Command Permissions
              if: inputs.os == 'ubuntu-latest'
              run: sudo chown root /bin/tar && sudo chmod u+s /bin/tar

            - name: Cache WX Ubuntu
              if: inputs.os == 'ubuntu-latest'
              id: cache-wx-ubuntu
              uses: actions/cache@v3
              with:
                path: /usr/local/wx_build/
                key: wx-build-3.2.4-ubuntu
                restore-keys: |
                  wx-build-3.2.4-ubuntu

            - name: Checkout WX Ubuntu
              if: inputs.os == 'ubuntu-latest' && steps.cache-wx-ubuntu.outputs.cache-hit != 'true'
              uses: actions/checkout@v3
              with:
                repository: WxWidgets/WxWidgets
                ref: v3.2.4
                path: ${{ github.workspace }}/wxWidgets
                submodules: 'true'

            - name: Configure WX Ubuntu
              if: inputs.os == 'ubuntu-latest' && steps.cache-wx-ubuntu.outputs.cache-hit != 'true'
              run: >
                cmake ${{ github.workspace  }}/wxWidgets
                -DCMAKE_INSTALL_PREFIX='/usr/local/wx_build'
                -DwxBUILD_SHARED=OFF
                -B ${{ github.workspace }}/wx-build-ubuntu

            - name: Build WX Ubuntu
              if: inputs.os == 'ubuntu-latest' && steps.cache-wx-ubuntu.outputs.cache-hit != 'true'
              run: > 
                sudo cmake --build ${{ github.workspace }}/wx-build-ubuntu --target install --config Release 
            
            - uses: actions/checkout@v3
              with:
                path: mfpg
                submodules: 'true'

            - name: Configure MFPG
              run: >
                cmake mfpg
                -B mfpg/mfpg_build
                -DCMAKE_CXX_COMPILER=${{ inputs.cxx-compiler }}
                -DCMAKE_C_COMPILER=${{ inputs.c-compiler }}
                -DCMAKE_BUILD_TYPE=${{ inputs.build-type }}
                -DREBUILD_MX=${{ inputs.mx-rebuild }}
                -DBUILD_TESTS=${{ inputs.build-tests }}
                -DWXW_ROOT_DIR="C:/Program Files (x86)/wxWidgets"
                -DWXW_LIB_DIR="C:/Program Files (x86)/wxWidgets/lib/vc_x64_lib"
                -DWXW_INC_DIR="C:/Program Files (x86)/wxWidgets/include"
                -DVER=${{ inputs.version }}
                
            - name: Build MFPG
              run: > 
                cmake 
                --build mfpg/mfpg_build 
                --config ${{ inputs.build-type }}

            - name: Test MFPG
              working-directory: mfpg/mfpg_build
              run: >
                ctest 
                --output-on-failure
                --build-config ${{ inputs.build-type }}
            
            - name: Rename Binaries Ubuntu
              if: inputs.upload-artifact && inputs.os == 'ubuntu-latest'
              run: |
                mv mfpg/mfpg_build/mfpg_gui mfpg/mfpg_build/mfpg_gui_linux-v${{ inputs.version }}
                mv mfpg/mfpg_build/mfpg mfpg/mfpg_build/mfpg_cli_linux-v${{ inputs.version }}
            
            - name: Rename Binaries Windows
              if: inputs.upload-artifact && inputs.os == 'windows-latest'
              run: |
                mv mfpg/mfpg_build/Release/mfpg_gui.exe mfpg/mfpg_build/Release/mfpg_gui_x86-v${{ inputs.version }}.exe
                mv mfpg/mfpg_build/Release/mfpg.exe mfpg/mfpg_build/Release/mfpg_cli_x86-v${{ inputs.version }}.exe

            - name: ZIP Artifact Ubuntu
              if: inputs.upload-artifact && inputs.os == 'ubuntu-latest'
              run: |
                mv mfpg/mfpg_build/mfpg_gui_linux-v${{ inputs.version }} .
                mv mfpg/mfpg_build/mfpg_cli_linux-v${{ inputs.version }} .
                mv mfpg/resources/xrc/resources.xrc .
                sudo tar -cf mfpg_linux.tar mfpg_gui_linux-v${{ inputs.version }} mfpg_cli_linux-v${{ inputs.version }} resources.xrc

            - name: Upload Artifact Ubuntu 
              if: inputs.upload-artifact && inputs.os == 'ubuntu-latest'
              uses: actions/upload-artifact@v4
              with:
                name: mfpg_artifact_ubuntu
                path: mfpg_linux.tar

            - name: Upload Artifact Windows 
              if: inputs.upload-artifact && inputs.os == 'windows-latest'
              uses: actions/upload-artifact@v4
              with:
                name: mfpg_artifact_windows
                path: |
                  mfpg/mfpg_build/Release/mfpg_gui_x86-v${{ inputs.version }}.exe
                  mfpg/mfpg_build/Release/mfpg_cli_x86-v${{ inputs.version }}.exe
                  mfpg/resources/xrc/resources.xrc

