name: Windows

on:
  pull_request:
    branches: [ "master" ]

jobs:
  windows-build-test:
    uses: ./.github/workflows/wf-main.yml
    with: 
      os: windows-latest
      c-compiler: cl
      cxx-compiler: cl
      mx-rebuild: false
      build-type: Release
