on:
  workflow_dispatch:
  push:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps: 
      - name: Get GTK
        run: |
          sudo apt-get install libgtk-3-dev
          sudo apt-get install libwxgtk3.0-gtk3-0v5
          sudo apt-get install libwxgtk3.0-gtk3-dev

      - name: Checkout MFPG
        uses: actions/checkout@v3
        with:
          path: mfpg
          submodules: 'true'

      - name: Configure MFPG
        run: >
          cmake mfpg -B mfpg_build-64

      - name: Build MFPG
        run: >
          cmake --build mfpg_build-64 --config Release 

