on:
  workflow_dispatch:
  push:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:


      - name: Cache WX
        id: cache-wx
        uses: actions/cache@v3
        with:
          path: C:/Program Files (x86)/wxWidgets
          key: wx-build-3.2.4-windows-${{ hashFiles('wx-build/config.log') }}
          restore-keys: |
            wx-build-3.2.4-windows-
      
      - name: Checkout WX
        uses: actions/checkout@v3
        with:
          repository: WxWidgets/WxWidgets
          ref: v3.2.4
          path: wxWidgets
          submodules: 'true'
      
      - name: Configure WX
        run: >
          cmake WxWidgets
          -DwxBUILD_SHARED=OFF
          -B wx-build

      - name: Build WX
        if: steps.cache-wx.outputs.cache-hit != 'true'
        run: >
          cmake --build wx-build --target install --config Release 

      - name: Checkout MFPG
        uses: actions/checkout@v3
        with:
          path: mfpg
          submodules: 'true'

      - name: Configure MFPG
        run: >
          cmake mfpg 
          -DWXW_ROOT_DIR="C:/Program Files (x86)/wxWidgets"
          -DWXW_LIB_DIR="C:/Program Files (x86)/wxWidgets/lib/vc_x64_lib"
          -DWXW_INC_DIR="C:/Program Files (x86)/wxWidgets/include"
          -B mfpg_build

      - name: Build MFPG
        run: >
          cmake --build mfpg_build --config Release 

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mfpg-gui
          path: mfpg_build/Release/mfpg_gui.exe
