on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout WX
        uses: actions/checkout@v3
        with:
          repository: WxWidgets/WxWidgets
          ref: v3.2.4
          path: wxWidgets
          submodules: 'true'

      - name: Cache WX
        id: cache-wx
        uses: actions/cache@v3
        with:
          path: wxWidgets/lib
          key: wx-3.2-4-build-lib-${{ runner.os }}-3264bit-static-staticrt-${{ hashFiles('wxWidgets/lib/config.log') }}
          restore-keys: |
            wx-3.2-4-build-lib-${{ runner.os }}-3264bit-static-staticrt-

      - name: Configure WX 64-bit
        run: |
          cmake WxWidgets -B build-64

        
