on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout WX
        uses: actions/checkout@v3
        with:
          repository: WxWidgets/WxWidgets
          ref: v3.2.4
          path: wxWidgets
          submodules: 'true'

      - name: Cache WX
        id: cache-wx
        uses: actions/cache@v3
        with:
          path: wxWidgets/lib
          key: wx-3.2-4-build-lib-${{ runner.os }}-3264bit-static-staticrt-${{ hashFiles('wxWidgets/lib/config.log') }}
          restore-keys: |
            wx-3.2-4-build-lib-${{ runner.os }}-3264bit-static-staticrt-

      - name: Configure WX 64-bit
        run: >
          cmake WxWidgets
          -DwxBUILD_SHARED=OFF
          -B build-64

      - name: Build WX 64-bit
        run: >
          cmake --build build-64 --target install 

      - name: Checkout MFPG
        uses: actions/checkout@v3
        with:
          path: mfpg
          submodules: 'true'

      - name: Configure MFPG
        run: >
          cmake mfpg 
          -DWXW_ROOT_DIR="C:/Program Files (x86)/wxWidgets"
          -DWXW_LIB_DIR="C:/Program Files (x86)/wxWidgets/lib"
          -DWXW_INC_DIR="C:/Program Files (x86)/wxWidgets/include"
          -B mfpg_build-64
