on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout WX
        uses: actions/checkout@v3
        with:
          repository: WxWidgets/WxWidgets
          ref: v3.2.4
          path: wxWidgets
          submodules: 'true'

      - name: Configure WX 64-bit
        run: >
          cmake WxWidgets
          -A x64
          -DwxBUILD_SHARED=OFF
          -B build-64

      - name: Build WX 64-bit
        run: >
          cmake --build build-64 --target install --config Release 

      - name: Checkout MFPG
        uses: actions/checkout@v3
        with:
          path: mfpg
          submodules: 'true'

            #      - name: Configure MFPG
            #        run: >
            #          cmake mfpg 
            #          -DWXW_ROOT_DIR="C:/Program Files (x86)/wxWidgets"
            #          -DWXW_LIB_DIR="C:/Program Files (x86)/wxWidgets/lib/vc_x64_lib"
            #          -DWXW_INC_DIR="C:/Program Files (x86)/wxWidgets/include"
            #          -B mfpg_build-64
      - name: Configure MFPG
        run: >
          cmake mfpg 
          -A x64
          -DWXW_ROOT_DIR="C:/Program Files/wxWidgets"
          -DWXW_LIB_DIR="C:/Program Files/wxWidgets/lib/vc_x64_lib"
          -DWXW_INC_DIR="C:/Program Files/wxWidgets/include"
          -B mfpg_build-64

      - name: Build MFPG
        run: >
          cmake --build mfpg_build-64 --config Release 

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: mfpg-x64-gui
          path: mfpg_build-64/Release/mfpg_gui.exe
